**(1)** Load the array you saved in the previous lesson from the disk.

In [ ]:
import numpy as np
data=np.load('b.npy')
data

array([[ 1.    ,  1.    ,  1.    ,  1.    ,  1.    ],
       [ 0.    , 37.4341, 35.852 ,  7.02  ,  4.1   ],
       [ 0.    , 37.6878, 37.4016, 10.27  ,  4.4   ],
       [ 0.    , 37.2003, 30.4376, 78.07  ,  4.    ],
       [ 0.    , 35.6846, 26.7266, 42.77  ,  4.5   ],
       [ 0.    , 36.4171, 28.6991, 14.86  ,  4.1   ],
       [ 0.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 0.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 0.    , 36.9653, 27.7633,  6.93  ,  4.3   ],
       [ 0.    , 38.893 , 26.4483, 11.62  ,  4.2   ],
       [ 0.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 0.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 0.    , 37.4635, 36.3113, 15.29  ,  4.3   ],
       [ 0.    , 37.0201, 36.0845, 10.    ,  4.1   ],
       [ 0.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 0.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 0.    , 39.0388, 44.1533,  7.52  ,  4.5   ],
       [ 0.    , 38.357 , 44.8686, 10.05  ,  4.1   ],
       [ 0.    , 35.7018, 28

**(2)** Display the mean and the standard deviation for each column.

In [ ]:
for i in range(0,len(data)):
    print("Mean of column {}                  :".format(i), np.mean(data[i]))
    print("Standart deviation of column {}    :".format(i),np.std(data[i]))
    print('\n')

Mean of column 0                  : 1.0
Standart deviation of column 0    : 0.0


Mean of column 1                  : 16.88122
Standart deviation of column 1    : 16.29656530295878


Mean of column 2                  : 17.951880000000003
Standart deviation of column 2    : 16.32625415536583


Mean of column 3                  : 29.94158
Standart deviation of column 3    : 28.066861774583916


Mean of column 4                  : 21.936240000000005
Standart deviation of column 4    : 16.918815549748157


Mean of column 5                  : 16.815239999999996
Standart deviation of column 5    : 13.955010798505317


Mean of column 6                  : 21.8294
Standart deviation of column 6    : 15.899599508792667


Mean of column 7                  : 24.589979999999997
Standart deviation of column 7    : 19.257083665228233


Mean of column 8                  : 15.19172
Standart deviation of column 8    : 14.490047261399804


Mean of column 9                  : 16.232260000000004
Standart d

In [ ]:
print(np.mean(data))

17.963437


**(3)** Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [ ]:
np.broadcast_to([1, 25, 25, 10, 4], (20, 5))
print(data-np.broadcast_to([1, 25, 25, 10, 4], (20, 5)))

[[ 0.00000e+00 -2.40000e+01 -2.40000e+01 -9.00000e+00 -3.00000e+00]
 [-1.00000e+00  1.24341e+01  1.08520e+01 -2.98000e+00  1.00000e-01]
 [-1.00000e+00  1.26878e+01  1.24016e+01  2.70000e-01  4.00000e-01]
 [-1.00000e+00  1.22003e+01  5.43760e+00  6.80700e+01  0.00000e+00]
 [-1.00000e+00  1.06846e+01  1.72660e+00  3.27700e+01  5.00000e-01]
 [-1.00000e+00  1.14171e+01  3.69910e+00  4.86000e+00  1.00000e-01]
 [-1.00000e+00  1.10535e+01  6.21350e+00  2.66800e+01  1.20000e+00]
 [-1.00000e+00  1.21958e+01  5.62410e+00  4.03300e+01  8.00000e-01]
 [-1.00000e+00  1.19653e+01  2.76330e+00 -3.07000e+00  3.00000e-01]
 [-1.00000e+00  1.38930e+01  1.44830e+00  1.62000e+00  2.00000e-01]
 [-1.00000e+00  1.23773e+01  1.13855e+01  5.30000e-01  8.00000e-01]
 [-1.00000e+00  1.08861e+01  1.06950e+00  1.84900e+01  9.00000e-01]
 [-1.00000e+00  1.24635e+01  1.13113e+01  5.29000e+00  3.00000e-01]
 [-1.00000e+00  1.20201e+01  1.10845e+01  0.00000e+00  1.00000e-01]
 [-1.00000e+00  1.26546e+01  1.66980e+00 -5.5000

In [ ]:
c= np.broadcast_to([1, 25, 25, 10, 4],(20,5))
print(np.array((data-c),dtype=np.int32))
#print(c)


[[  0 -24 -24  -9  -3]
 [ -1  12  10  -2   0]
 [ -1  12  12   0   0]
 [ -1  12   5  68   0]
 [ -1  10   1  32   0]
 [ -1  11   3   4   0]
 [ -1  11   6  26   1]
 [ -1  12   5  40   0]
 [ -1  11   2  -3   0]
 [ -1  13   1   1   0]
 [ -1  12  11   0   0]
 [ -1  10   1  18   0]
 [ -1  12  11   5   0]
 [ -1  12  11   0   0]
 [ -1  12   1  -5   0]
 [ -1  12   4   7   0]
 [ -1  14  19  -2   0]
 [ -1  13  19   0   0]
 [ -1  10   3  -3   0]
 [ -1  12  12   0   0]]


In [ ]:
#print(np.subtract(data[:1], c[:1]))
#data[:,1]-=25

**(4)** Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [ ]:
final = asi *2
print(final)

[[  0 -48 -48 -18  -6]
 [ -2  24  20  -4   0]
 [ -2  24  24   0   0]
 [ -2  24  10 136   0]
 [ -2  20   2  64   0]
 [ -2  22   6   8   0]
 [ -2  22  12  52   2]
 [ -2  24  10  80   0]
 [ -2  22   4  -6   0]
 [ -2  26   2   2   0]
 [ -2  24  22   0   0]
 [ -2  20   2  36   0]
 [ -2  24  22  10   0]
 [ -2  24  22   0   0]
 [ -2  24   2 -10   0]
 [ -2  24   8  14   0]
 [ -2  28  38  -4   0]
 [ -2  26  38   0   0]
 [ -2  20   6  -6   0]
 [ -2  24  24   0   0]]
