**(1)** Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [ ]:
import numpy as np
squaremeter = list(range(150,190,4))
rooms = list(range(2,12))
price = list(range(300000,300020,2))

final=np.array((squaremeter,rooms,price))

print(final)

[[   150    154    158    162    166    170    174    178    182    186]
 [     2      3      4      5      6      7      8      9     10     11]
 [300000 300002 300004 300006 300008 300010 300012 300014 300016 300018]]


**(2)** Transpose the array you have created, so that every line can represent features of one house.

In [ ]:
np.transpose(final)

array([[   150,      2, 300000],
       [   154,      3, 300002],
       [   158,      4, 300004],
       [   162,      5, 300006],
       [   166,      6, 300008],
       [   170,      7, 300010],
       [   174,      8, 300012],
       [   178,      9, 300014],
       [   182,     10, 300016],
       [   186,     11, 300018]])

**(3)** Display the shape of the array and explain what it means.

In [ ]:
np.transpose(final).shape  # Output says; This figure is a matrix structure consisting of 3 columns and 10 rows. 

(10, 3)

**(4)** Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [ ]:
import numpy as np

def num_array(x,y):
  a= np.zeros((x,y))
  for i in [ i for i in range(x) if i%2==0]:
    a[:,i]=1
  for i in [ i for i in range(y) if i%2==0]:
    a[i,:]=1 
  return a

n_rows = int(input("Enter number of rows: "))
n_cols = int(input("Enter number of columns: "))

print(num_array(n_rows,n_cols))

Enter number of rows: 6
Enter number of columns: 5
[[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]]
